### PR TITLE
Stage 3 - Results

### PR DESCRIPTION
**Pull request by gent1999**
When the admin clicks on the "results time" button on the event, the stage will move to 3. It will make a call to the backend to average all votes and update the "average_score" in the ideas db. 
On the user side of the event, you will the ideas ranked in order from highest score to lowest.

### CODE REVIEW

**Review by benhuangbmj — COMMENTED** [review]
@gent1999  Does the Vercel preview block public access?

**Comment by gent1999** [comment]
Yeah its never worked for me.

**Review by sgopalani12 — APPROVED** [review]
Looks good

**Comment by benhuangbmj** [comment]
> Yeah its never worked for me.

@gent1999 
You can try disable the deployment protection from the project settings.
image

**Pull request merged**
